// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://debchqkkydrxqrvyyuxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlYmNocWtreWRyeHFydnl5dXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTM3MTAsImV4cCI6MjA2NzcyOTcxMH0.Nm6QQMv5NYtzDl1kqXQ0ayZxg_GE1eysunoGC9qbQBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});